### ISSUE TITLE
Single-file content products is generating blank PDFs

### ISSUE THREAD

**Issue by gsong** [EnterpriseDB/docs#1290]
The root cause of this issue is because `generate_pdf.py` assumes that any paths with 4 elements in the input path, e.g. `product_docs/docs/bdr/3.6`, is a `fullProductPdf`.

<https://github.com/EnterpriseDB/docs/blob/develop/scripts/pdf/generate_pdf.py#L138-L139> then removes the first file from the file entries to be converted to PDF, in this case the only file in this directory.

<details>
<summary>I believe all these products suffer from this problem</summary>

```
product_docs/docs/bart/2.4
product_docs/docs/bart/2.5.1
product_docs/docs/bart/2.5.2
product_docs/docs/bart/2.5.3
product_docs/docs/bart/2.5.4
product_docs/docs/bart/2.5.5
product_docs/docs/bart/2.5.7
product_docs/docs/bdr/3.6
product_docs/docs/efm/3.10
product_docs/docs/efm/3.6
product_docs/docs/efm/3.7
product_docs/docs/efm/3.8
product_docs/docs/efm/3.9
product_docs/docs/epas/10
product_docs/docs/epas/11
product_docs/docs/epas/12
product_docs/docs/epas/9.5
product_docs/docs/epas/9.6
product_docs/docs/hadoop_data_adapter/2.0.5
product_docs/docs/hadoop_data_adapter/2.0
product_docs/docs/jdbc_connector/42.2.12.1
product_docs/docs/jdbc_connector/42.2.8.1
product_docs/docs/jdbc_connector/42.2.9.1
product_docs/docs/migration_toolkit/53.0.1
product_docs/docs/net_connector/4.0.10.1
product_docs/docs/net_connector/4.0.10.2
product_docs/docs/net_connector/4.0.6.1
product_docs/docs/net_connector/4.1.3.1
product_docs/docs/net_connector/4.1.5.1
product_docs/docs/ocl_connector/12.1.2.1
product_docs/docs/ocl_connector/13.1.4.1
product_docs/docs/odbc_connector/12.0.0.1
product_docs/docs/odbc_connector/12.0.0.2
product_docs/docs/odbc_connector/12.2.0.1
product_docs/docs/pem/7.10
product_docs/docs/pem/7.11
product_docs/docs/pem/7.12
product_docs/docs/pem/7.13
product_docs/docs/pem/7.14
product_docs/docs/pem/7.15
product_docs/docs/pem/7.6
product_docs/docs/pem/7.7
product_docs/docs/pem/7.8
product_docs/docs/pem/7.9
product_docs/docs/repmgr/5.2.1
```

</details>

## ~~Short-Term Solution~~

~~For any directories with a single file, don't produce PDFs.~~

The proposed short-term solution doesn't work because it further hides the problem of top-level `index.mdx` with content.

## Solution

Refactor code to handle the top-level `index.mdx` file properly, depending on
if it contains content or not.

[Work in progress](https://github.com/EnterpriseDB/docs/pull/1460)

## TODOs

- [ ] Top level peers to `index.mdx` are not considered sub-chapters, but true peers
- [ ] Enhance diff script to compare two files
- [ ] Enhance diff script to produce text diffs

**Comment by gsong** [comment]
@josh-heyer @cero-miedo What should the solution be? I don't know the content as well so it's hard for me to say what the generalized rules are.

**Comment by bradnoble** [comment]
I wish there was a way to use inheritable front matter to flag directories that should be built into PDFs.

**Comment by cero-miedo** [comment]
Relates to: #1205

**Comment by abhilasha-narendra** [comment]
I commented out the if statement on lines 138 and 139 of generate_pdf.py file, and now the PDF generation script is working fine on my local system.  I tested it with BDR, Pgpool, EFM, and EPAS guides and all these PDFs now contain the content of index.mdx file.

**Comment by gsong** [comment]
@abhilasha-narendra How about <https://raw.githubusercontent.com/EnterpriseDB/docs/develop/product_docs/docs/ark/3.5/index.mdx>?

If we remove those lines, we get a chapter 0: [ark-toc.pdf](https://github.com/EnterpriseDB/docs/files/6632346/ark-toc.pdf)

**Comment by abhilasha-narendra** [comment]
@gsong Ark documentation is no longer updated that's why there is no content on the index.mdx. Probably we can treat Ark as an exception.

**Comment by gsong** [comment]
@abhilasha-narendra I'm in the process of refactoring that script, and will take your suggestion into account.

**Comment by gsong** [comment]
@josh-heyer @jericson-edb @robert-stringer @abhilasha-narendra In solving this issue, I've started the path of refactoring the PDF generation script. I've discovered some bugs with the current script that are related to this issue. As @abhilasha-narendra mentioned, there are indeed top-level `index.mdx` files with content, which we're incorrectly stripping out right now during PDF generation.

I've resolved this issue by introspecting all `*.mdx` files and filtering out ones that contain only front matter or the `<StubCards>` component in its body.

1. Using this algorithm, we reduce the number of generated PDFs from 55 to 35. [See which PDFs are no longer generated](https://drive.google.com/file/d/17muRj-wFWlsRFYYbcLuWKTqsAXARdNpr/view?usp=sharing).
1. For products such as BDR with just `index.mdx`, [the PDF now contains the content](https://drive.google.com/file/d/1kwNdP_Za_lENtz3zoUleHe62UqlL0EZF/view?usp=sharing).
1. However, this presents a different issue for chapter number for products that have content in `index.mdx` _and_ other content, such as [EDB OCL Connector](https://drive.google.com/file/d/1IuU1LnvqtkOJydEUrUVyn8qeuVxyK5A1/view?usp=sharing).

   Because of the way the chapter numbering algorithm works, the content at the same level as `index.mdx` are considered part of the same chapter. The peer files and directories of the top-level `index.mdx` are now numbered 1.1, 1.2, and so on. Is this the right behavior?

Unrelated to the top-level `index.mdx` issue is the current chapter numbering algorithm also has subtle bugs, e.g. [EPAS 13](https://drive.google.com/file/d/170D-iuz4MFZx24CML8_mqDeL4AwrvX2z/view?usp=sharing) jumps from chpater 20 to 22.

## Reference Files

I've staged [a folder with the following artifacts on Google drive](https://drive.google.com/drive/folders/1eLSeYFWlgr6IU6OedAXEFbqRoA8utr5S?usp=sharing):

- [Generated PDFs in `develop`](https://drive.google.com/drive/folders/1SaMwrMsvDMPdYs5yvzzyinQggleGwfwb?usp=sharing)
- [Generted PDFs from this PR](https://drive.google.com/drive/folders/1sxveQHJvIq7cRe8VL9gnJMJg5odQFJ-n?usp=sharing)
- [Visual diffs between the two sets](https://drive.google.com/drive/folders/15AkW-PPhSvbFRupnH3J9XovaT4BakScW?usp=sharing)
- [List of removed PDFs](https://drive.google.com/file/d/17muRj-wFWlsRFYYbcLuWKTqsAXARdNpr/view?usp=sharing)

## What I Need Your Help With

- [ ] Verify the removed PDFs are all in fact blank in `develop`.
- [ ] Inspect the visual diffs to make sure everythings looks OK.
- [ ] Decide on the desired chapter numbering behavior.

**Comment by josh-heyer** [comment]
FWIW, I don't *think* the numbering corresponds to anything; we certainly don't seem to have tried to make it match the old PDFs.

**Comment by jericson-edb** [comment]
I did find something in the [odbc_connector_v13.0.0.0_documentation.pdf](https://drive.google.com/drive/folders/1SaMwrMsvDMPdYs5yvzzyinQggleGwfwb) file on GDrive.

**Comment by gsong** [comment]
@jericson-edb That was a misplaced PDF in the current `develop` branch. Notice that there's no v13.0.0.0 for that product.

<https://github.com/EnterpriseDB/docs/blob/develop/product_docs/docs/odbc_connector/13.0.0.1/odbc_connector_v13.0.0.0_documentation.pdf>

**Comment by gsong** [comment]
Reply to [@bradnoble's comment](#issuecomment-827622450):

> I wish there was a way to use inheritable front matter to flag directories that should be built into PDFs.

@bradnoble If we want to be able to manually specify which products should be included or ignored, we can parse for that info during PDF generation. What's the use case?

**Comment by jericson-edb** [comment]
@gsong Good deal. I was wondering why I hadn't seen it in my local copy of the repository.

I checked the index.mdx files in that list to see if there was anything that should have been saved to PDF. All are blank other than frontmatter and a StubCards tag:

```
<StubCards product='efm' version='3.10' />
```

Here's the script I used to check the files:

```
$ echo 'efm_v3.10_documentation.pdf
efm_v3.7_documentation.pdf
efm_v3.8_documentation.pdf
efm_v3.9_documentation.pdf
epas_v10_documentation.pdf
epas_v11_documentation.pdf
epas_v9.6_documentation.pdf
jdbc_connector_v42.2.8.1_documentation.pdf
jdbc_connector_v42.2.9.1_documentation.pdf
net_connector_v4.0.10.1_documentation.pdf
net_connector_v4.0.6.1_documentation.pdf
net_connector_v4.1.3.1_documentation.pdf
net_connector_v4.1.5.1_documentation.pdf
odbc_connector_v13.0.0.0_documentation.pdf
pem_v7.10_documentation.pdf
pem_v7.11_documentation.pdf
pem_v7.12_documentation.pdf
pem_v7.13_documentation.pdf
pem_v7.14_documentation.pdf
pem_v7.15_documentation.pdf' | perl -nlpe 's|_v([0-9.]+)_|/\1/|;s|^|product_docs/docs/|;s/documentation.pdf/index.mdx/' | xargs less
```

In less, use `:n` to look at the next file.

**Comment by abhilasha-narendra** [comment]
@gsong I verified the list of removed PDFs and all of these PDFs belong to versions having stub entries, hence this approach looks fine to me. 
The numbering of chapters and sections is definitely something that we need to work upon. Probably we can check for content in the base index.mdx and if it is not blank then increase the chapter counter with one.

**Comment by josh-heyer** [comment]
I reviewed the diffs; some odd spacing changes, but guessing that's probably unrelated.

Also not introduced in this change, but somewhat more concerning: the header rewriting (lines 51-54 in the revised script) isn't aware of code blocks. That leads to unnecessary prefixes when hashes are used for comments (e.g. page 49 of efm_v4.2_documentation.pdf). Shouldn't matter in practice, but not ideal.

I like @abhilasha-narendra's suggestion for numbering.

**Comment by gsong** [comment]
@josh-heyer Can you please file a separate issue regarding the header rewriting, including a specific example? Thanks.
