### ISSUE TITLE
Tracking: tasks to complete before retiring Docs 1.0 

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#1538]
- [] OpenAPI HTML gen
- [] Enable rel:canonical header (ref: #163 - this was disabled at some point during release)
- [] Merge archive component (ref: #1368)
- [] Update extant links to docs 1.0 within the docs themselves
- [] Test Netlify redirects
- [] Update legacy redirects
- [] Send legacy redirects to IT
- [] Remove beta label on logo
- [] Remove beta banner ("This is the redesigned EDB Docs site. For older product docs, go to theEDB Docs Archive")

**Comment by frago12** [comment]
@josh-heyer The archive component was merged into `develop` as part of #1549
